blank_issues_enabled: false
contact_links:
  - name: Kontakt
    url: https://www.gov.tum.de/elaw/team/michael-bressler/
    about: Bei Fragen und Problemen kannst du dich gerne an unseren zuständigen Mitarbeiter (Michael Bressler) wenden!   Ihr Lehrstuhl für Recht und Sicherheit der Digitalisierung
