blank_issues_enabled: false
contact_links:
  - name: Lehrstuhl für Recht und Sicherheit der Digitalisierung
    url: https://www.gov.tum.de/elaw/team/michael-bressler/
    about: Bei Fragen und Problemen kannst du dich gerne an unseren Wikiadmin (Michael Bressler) melden!
